import type { Engine, JobTag, Raster } from "../engine/index.js";
import type { Fit } from "./transform.js";
import type { Document } from "./types.js";
import { fail } from "./types.js";

/** One downloadable artifact, including an optional georeferencing sidecar. */
export interface ExportFile {
  /** Suggested filename including extension. */
  name: string;
  /** Locally generated bytes; the host owns any download URL it creates. */
  blob: Blob;
}

/** Output of an exporter before the controller attaches revision provenance. */
export interface ExportContent {
  /** Primary artifact, also present as the first entry in files. */
  blob: Blob;
  /** Primary artifact and any required sidecars, in download order. */
  files: ExportFile[];
  /** Optional full-resolution rendered pixels; never the shared preview buffer. */
  raster?: Raster;
  /** Optional original-pixel placement for a world-file export. */
  worldFile?: {
    /** Six world-file lines in A, D, B, E, C, F order. */
    text: string;
    /** Explicit CRS, since world-file text cannot carry it. */
    crs: string;
  };
}

/** Immutable revision provenance plus the artifacts produced for that revision. */
export interface ExportResult extends ExportContent {
  /** Configured format identifier. */
  format: string;
  /** Frozen document snapshot actually processed, even if newer edits exist. */
  document: Document;
}

/** Captured inputs for one export. Never mutate or retain shared preview pixels. */
export interface ExportContext {
  /** Exact frozen revision to process. */
  document: Document;
  /** Current fit, or null for formats permitting unfinished sessions. */
  fit: Fit | null;
  /** Read-only borrowed preview for reports; never transfer its data buffer. */
  preview: Raster | null;
  /** Original local bytes; present for image-dependent exports. */
  file: File | null;
  /** Host processing engine, retaining its configured limits/projections/scheduler. */
  engine: Engine;
  /** Revision identity for worker jobs. */
  tag: JobTag;
  /** Aborted on cancellation, supersession, re-alignment or suspension. */
  signal: AbortSignal;
  /** Report normalized progress from 0 to 1. */
  onProgress: (fraction: number) => void;
}

/** Lazily loaded format implementation. Hosts may implement their own exporters. */
export interface Exporter {
  /** Generate local artifacts; respect cancellation and preserve snapshot identity. */
  run(context: ExportContext): Promise<ExportContent>;
}

/** Small format descriptor registered explicitly in controller configuration. */
export interface ExportFormat {
  /** Unique stable format ID within this controller. */
  id: string;
  /** Default English action label, passed through the React translation hook. */
  label: string;
  /** Whether to expose shared raster output controls for this format. */
  raster?: boolean;
  /** Whether a valid current fit is required; defaults to true. */
  requiresFit?: boolean;
  /** Additional eligibility explanation, or null when eligible. Must be pure. */
  unavailable?: (document: Document, fit: Fit | null) => string | null;
  /** Load implementation on use, not during registration or React rendering. */
  load: () => Promise<Exporter>;
}

/**
 * Await lazy/plugin work while making abort immediately observable. Downloading an
 * imported module cannot be undone; its eventual result is ignored after abort.
 * @internal
 */
export function abortable<T>(
  promise: Promise<T>,
  signal: AbortSignal,
): Promise<T> {
  return new Promise((resolve, reject) => {
    const cancel = () => reject(new DOMException("Cancelled", "AbortError"));
    if (signal.aborted) {
      promise.catch(() => {});
      cancel();
      return;
    }
    signal.addEventListener("abort", cancel, { once: true });
    promise
      .then(resolve, reject)
      .finally(() => signal.removeEventListener("abort", cancel));
  });
}
/**
 * Copy and validate descriptors without loading plugin implementations.
 * @throws {@link GeoreferenceError} For missing or duplicate IDs, labels or loaders.
 * @internal
 */
export function validateExportFormats(
  formats: readonly ExportFormat[],
): readonly ExportFormat[] {
  const ids = new Set<string>();
  return Object.freeze(
    formats.map((format) => {
      if (
        !format.id ||
        ids.has(format.id) ||
        !format.label ||
        typeof format.load !== "function"
      )
        fail(
          "EXPORT_CONFIG",
          "Export formats require unique IDs, labels and lazy loaders.",
        );
      ids.add(format.id);
      return Object.freeze({ ...format });
    }),
  );
}
